export enum clientEnum {
  miguelRivas = 100,
  presidente,
  drLogic,
  descubria,
  capitalDBG,
  pepsi,
  redRock,
  itla,
  pixelPerfectTree,
  bprBank,
  voxel,
  orange,
  apap,
  enovational,
  socialNetwork,
  jellyfish,
  plantTherapy,
}

export const client = {
  presidente: "Cerveza Presidente",
  drLogic: "DrLogic",
  descubria: "Descubria",
  capitalDBG: "Capital DBG",
  miguelRivas: "Miguel Rivas",
  pepsi: "Pepsi",
  redRock: "Red Rock",
  itla: "ITLA",
  pixelPerfectTree: "Pixel Perfect Tree",
  bprBank: "BPR Bank",
  voxel: "Voxel Cube Games",
  orange: "Orange",
  apap: "APAP",
  enovational: "Enovational",
  socialNetwork: "Social Network",
  jellyfish: "Jellyfish",
  plantTherapy: "Plant Therapy",
};