export enum toolEnum {
  html = 100,
  erb,
  pug,
  jade,
  haml,
  slim,
  svg,

  css = 150,
  scss,
  sass,
  less,

  javascript = 200,
  jQuery,
  vue,
  vuex,
  vueRouter,
  angular,
  react,
  redux,
  snapSVG,
  chartJS,
  tweenMax,
  three,
  json,
  typescript,
  sizzle,
  lodash,
  velocity,
  canvas,
  sweetAlert,
  stellar,
  highlight,

  rails = 250,
  php,
  python,

  grunt = 300,
  gulp,
  webpack,

  git = 350,

  flash = 400,
  illustrator,
  photoshop,
  indesign,
  afterEffects,
  premiere,
  inkscape,
  scribus,

  bootstrap = 450,
  animate,

  cucumber = 500,
  jest,
  
  firebase = 550,
  mysql,
  mongo,

  unity = 600,
  blender,
  maya,

  kotlin = 650,

  miva = 700,
  wordpress,
  drupal,
  joomla,
  
  markdown = 750,
}

export const tool = {
  html: "HTML",
  erb: "HTML/ERB",
  pug: "Pug",
  jade: "Pug",
  haml: "Haml",
  slim: "Slim",
  css: "CSS",
  sass: "SCSS",
  scss: "SCSS",
  less: "Less",
  cucumber: "Cucumber",
  unity: "Unity",
  rails: "Ruby on Rails",
  php: "PHP",
  python: "Python",
  javascript: "Javascript",
  vue: "Vue",
  angular: "Angular",
  react: "React",
  grunt: "GruntJS",
  three: "ThreeJS",
  jQuery: "jQuery",
  json: "JSON",
  miva: "Miva",
  markdown: "Markdown",
  bootstrap: "Bootstrap",
  git: "Git",
  flash: "Adobe Flash",
  illustrator: "Adobe Illustrator",
  photoshop: "Adobe Photoshop",
  indesign: "Adobe Indesign",
  afterEffects: "Adobe After Effects",
  premiere: "Adobe Premiere",
  inkscape: "Inkscape",
  typescript: "TypeScript",
  vuex: "Vuex",
  vueRouter: "Vue Router",
  sizzle: "Sizzle",
  lodash: "Lodash",
  velocity: "Velocity.js",
  canvas: "Canvas",
  sweetAlert: "Sweetalert",
  stellar: "stellarJS",
  animate: "Animate CSS",
  snapSVG: "snapSVG",
  chartJS: "ChartJS",
  wordpress: "Wordpress",
  kotlin: "Kotlin",
  tweenMax: "TweenMax",
  firebase: "Firebase",
  webpack: "Webpack",
  mysql: "MySQL",
  jest: "Jest",
  blender: "Blender",
  maya: "Maya",
  drupal: "Drupal",
  scribus: "Scribus",
  redux: "Redux",
  mongo: "MongoDB",
  gulp: "Gulp",
  svg: "SVG",
  joomla: "Joomla",
  highlight: "Highlight.js"
};